### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by muntaqam** [muntaqam/GOODREAD-CLONE-NEXTJS#18]
### AUTH
- [x] can register
- [x] can log in
- [x] can not register email that has alrdy been registered
- [x] can log out
- [x] when logged out cant access dashboard

### search books
- [x] can search from homepage 
- [x] can search from navbar
- [x] can click on books from searches

### book details
- [x] book title,author, cover is visible
- [x] can rate books
- [x] can view avg rating 
- [x] delete rating 
- [x] deleted rating reflects avg rating
- [x] can add reviews
- [x] review displays w username
- [x] user can only review once per book even when user refreshs
- [x] can add book to shelf 

### dashboard

- [x] shelves are visible
- [x] shelves reflect books that were added
- [x] can remove shelved books
- [x] can access book details by clicking on books in shelves
