### ISSUE TITLE
checklist P2

### ISSUE THREAD

**Issue by muntaqam** [muntaqam/GOODREAD-CLONE-NEXTJS#19]
**Book Shelf**
- [x] when book is added to shelf then there should be some sort of positive feedback so users know its added
- [x] a book can be added to a shelf (unique)
- [x] if a book is being added again to a shelf , errror message saying the book is alrdy on the shelf
- [x] when u remove a book u should get feedback saying you removed the book 
- [ ] only the booklist should be scrollable the hwole page shouldnt scroll
- [x] if a book image is not available it should show default img

**Discover Page**
- [x] when u click on a book it should take it to book[id] page
- [x] search button , make it in a mini screen
- [x] add autocomplete to search button 
- [x] style arrows - removed them
- [ ] style scrollbar
- [x] add arrows 

**Book Details**
- [x] style the alert where it alerts user that theyre changing thier rating - unnecesary 
- [x] when updating comment, the relative time should show 
- [x] profile pic should show for user review
- [ ] add genre bubbles in the bottom - problem bc some dont have genre section
- [x] when u search a diff book then the one that is shown the review doesnt show until u refresh it 
- [x] change color of the write a review..

**Search bar in nav**
- [x] if user doesnt chose a title from the options instead clicks enter or search icon then it should show the search list page
- [x] text is white, change to visible color 
- [x] when user presses enter u get an error 
- [x] use the SearchBar.js component in Navbar

**dashboard**
- [x] close button doesnt work
- [x] when user clicks outside of modal it should close 
- [x] book is visible in dashboard after adding it but it is uncategorized and pic is not shown until u refresh or go to the specific bookshelf
- [x] when u hover over the user profile card it should show edit button 
- [ ] the grey are behind the profile pic , do something with it, maybe add waves or something 
- [ ] style the cards 
- [ ] when user changes thier pic then the modal should close automaticaly 

**Reviews**
- [x] when u update review the relative time should also update

**Screens**
- [x] add loading screen 
- [ ] add error not found page

**register**
- [ ] add forget password option
- [x] make a dummy guest login account

-fontpair 
-https://haikei.app/
