### ISSUE TITLE
checklist p3

### ISSUE THREAD

**Issue by muntaqam** [muntaqam/GOODREAD-CLONE-NEXTJS#20]
Issues

- [ ] when u log out and go to dashboard the previos dashboard flashes before redirected to /auth
- [ ] the books from nyt times list book[id] is diff from the google api one 
- [x] add a logo or the word "greatreads" on the auth page
- [ ] when u search sometimes if thummbnai not found it crashes , do if error then dont load it if it doesnt have
- [x] when user hover over a book , cursor should be a hand
- [x] when user hovers at the navbar drop down it should be a hand
